name: Docker Build
description: Build and push a Docker image
inputs:
  username:
    description: 'The username for docker login'
    required: true
  password:
    description: 'The password for docker login'
    required: true
  docker-repo:
    description: 'The docker container name'
    required: true
  tag:
    description: 'Tag for the Docker image'
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ inputs.docker-repo }}:${{ inputs.tag }} .
      shell: bash

    - name: Push Docker Image
      run: |
        docker push ${{ inputs.docker-repo }}:${{ inputs.tag }}
      shell: bash
